# -*- coding: utf-8 -*-
"""SkewKurt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y-CnLzzLvAx-Np6zBzvY1oH0hO4TXmhW
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
from scipy.stats import skew, kurtosis, mode #Python libraries for inferential statistics
import seaborn as sns #This is for generating Histogram with Ker

df = pd.read_csv('/content/sample_data/hotel_books.csv') #uread the 'hotel_books.csv' file
df.head(5)

df.dtypes #check for data types

df.isnull().sum() #check for missing values

sns.histplot(df['clients'], kde=True) #generate histogram with kernel density estimate (KDE) for number of hotel clients

sns.histplot(df['total_bill'], kde=True) #generate histogram with kernel density estimate (KDE) for total bill collected

#compute for skewness and kurtosis for number of clients
skew1 = df['clients'].skew()
kurt1 = df['clients'].kurt()
print(f'Kurtosis for the number of hotel clients in a day:{kurt1}')
print(f'Skewness for the number of hotel clients in a day:{skew1}')

#compute for skewness and kurtosis for total number of bill
skew2 = df['total_bill'].skew()
kurt2 = df['total_bill'].kurt()
print(f'Kurtosis for the total bill collected from clients per day:{kurt2}')
print(f'Skewness for the total bill collected from clients per day:{skew2}')

df.describe() #generate summary measure and observe the mean and 50% (median)

stats.mode(df['clients']) #compute for mode

stats.mode(df['total_bill']) #compute for mode

